# https://github.com/marketplace/actions/electronegativity
name: Security analysis
on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Dependencies
        run: yarn
      - uses: doyensec/electronegativity-action@v1.1
      - uses: github/codeql-action/upload-sarif@v1
